export default function Head() {
  return (
    <head>
      <title>Transtama - HRIS</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </head>
  );
}
